# Generated by Django 2.0.6 on 2018-06-26 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0002_label_lane_projectmember_task_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='userid',
            new_name='loginid',
        ),
    ]
