# Generated by Django 2.0.6 on 2018-07-11 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0003_auto_20180626_2330'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
