# Generated by Django 2.0.7 on 2018-08-15 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0004_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='label_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
